# simplified haskell-ci Travis setup
# see also https://github.com/haskell-CI/haskell-ci

language: haskell
sudo: enabled
services:
  - docker

cache:
  directories:
   - $HOME/.cabal/store

matrix:
  include:
    - ghc: "8.8.1"
      cabal: 3.0
      env: TARGET=cabal.88.project
    - ghc: "8.6.5"
      cabal: 2.4
      env: TARGET=cabal.project
    - ghc: "8.4.4"
      cabal: 2.4
      env: TARGET=cabal.project
    - ghc: "8.2.2"
      cabal: 2.4
      env: TARGET=cabal.project
    - ghc: "8.0.2"
      cabal: 2.4
      env: TARGET=cabal.project

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-build all --project-file=$TARGET
 - cabal v2-test all --enable-test --project-file=$TARGET
 - if ghc --version | grep -q 8.8.1; then bash script/deploy.sh; fi
