name:                boots
version:             0.0.2
synopsis:            Boot application by plugins
description:         Boot application by using plugins.
homepage:            https://github.com/leptonyu/boots#readme
license:             MIT
author:              Daniel YU
maintainer:          leptonyu@gmail.com
copyright:           2019 Daniel YU
category:            Library
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - exceptions
  - mtl
  - unliftio-core
  - salak
  - salak-yaml
  - microlens
  - monad-logger
  - fast-logger
  - text
  - data-default

default-extensions:
  - FlexibleInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - RecordWildCards
  - FlexibleContexts
  - RankNTypes
  - ScopedTypeVariables

library:
  source-dirs: src
  exposed-modules:
    - Boots

    - Boots.Plugin
    - Boots.Plugin.Simple
    - Boots.Plugin.Salak
    - Boots.Plugin.Logger
    
  other-modules:
    - Boots.Internal

    - Boots.Internal.App
    - Boots.Internal.Plugin

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*

executables:
  boots-exe:
    source-dirs:      main
    main:             Main.hs
    dependencies:
      - boots
