resolver: nightly-2019-09-02

packages:
- boots
- boots-app
- boots-cloud
- boots-web

- demo

extra-deps:
- git: https://github.com/kazu-yamamoto/logger.git
  commit: fc8a7c8275c802d713355aac7a2c55454728d17b
  subdirs:
  - fast-logger
- warp-3.3.0
- http2-2.0.3
# - time-1.9.3

ghc-options:
  "$locals": -ddump-to-file -ddump-hi
