resolver: nightly-2019-08-26

packages:
- boots
- boots-app
- boots-cloud
- boots-web

- demo

extra-deps:
- warp-3.3.0
- http2-2.0.3
# - time-1.9.3

# ghc-options:
#   "$locals": -ddump-to-file -ddump-hi
