resolver: nightly-2019-08-07

packages:
- boots
- boots-app

extra-deps:
- git: https://github.com/leptonyu/salak.git 
  commit: 61932dc9b7a13725faa1257dad9fdc90b156d388
  subdirs:
  - salak
  - salak-yaml

pvp-bounds: both
