_common: !include "../common.yaml"
name:                boots-cloud
synopsis:            Factory for quickly building a microservice
description:         A quick out-of-box factory using to build microservices with many useful builtin components based on [boots-web](https://hackage.haskell.org/package/boots-web).
category:            Library, Application, Servant, Swagger, Web, Microservice, Consul
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base          >= 4.10   && < 5

library:
  source-dirs: src
  exposed-modules:
    - Boots.Cloud
  other-modules:
    - Network.Consul
    - Boots.Factory.Consul
    - Boots.Factory.Client
  dependencies:
    - aeson                >= 1.4.4  && < 1.5
    - boots                >= 0.2    && < 0.3
    - boots-app            >= 0.2    && < 0.3
    - boots-web            >= 0.2    && < 0.3
    - bytestring           >= 0.10.8 && < 0.11
    - http-client          >= 0.6.4  && < 0.7
    - salak                >= 0.3.5  && < 0.4
    - servant              >= 0.16.2 && < 0.17
    - servant-client       >= 0.16   && < 0.17
    - text                 >= 1.2.3  && < 1.3
    - unordered-containers >= 0.2.10 && < 0.3

