_common: !include "../common.yaml"
name:                boots-web
synopsis:            Factory for quickly building a web application
description:         A quick out-of-box factory using to build web application with many useful builtin components based on [boots](https://hackage.haskell.org/package/boots) and [servant](https://hackage.haskell.org/package/servant).
category:            Library, Application, Servant, Swagger, Web
<<: *legal
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base          >= 4.10   && < 5

library:
  source-dirs: src
  exposed-modules:
    - Boots.Web

    - Boots.Factory.Endpoint
    - Boots.Factory.Error 
    - Boots.Factory.Random
    - Boots.Factory.Trace

  other-modules:
    - Boots.Factory.Web
    - Boots.Metrics

    - Boots.Endpoint.Class
    - Boots.Endpoint.Health
    - Boots.Endpoint.Info
    - Boots.Endpoint.Logger
    - Boots.Endpoint.Metrics
    - Boots.Endpoint.Refresh
    - Boots.Endpoint.Swagger
  dependencies:
    - aeson                >= 1.4.4   && < 1.5
    - boots                >= 0.2     && < 0.3
    - boots-app            >= 0.2     && < 0.3
    - bytestring           >= 0.10.8  && < 0.11
    - containers           >= 0.6.0   && < 0.7
    - ekg-core             >= 0.1.1   && < 0.2
    - http-types           >= 0.12.3  && < 0.13
    - microlens            >= 0.4.10 && < 0.5
    - monad-logger         >= 0.3.30  && < 0.4
    - salak                >= 0.3.5   && < 0.4
    - servant-server       >= 0.16.2  && < 0.17
    - servant-swagger      >= 1.1.7.1 && < 1.2
    - swagger2             >= 2.4     && < 2.5
    - text                 >= 1.2.3   && < 1.3
    - time                 >= 1.8.0   && < 1.10
    - unordered-containers >= 0.2.10  && < 0.3
    - vault                >= 0.3.1   && < 0.4
    - wai                  >= 3.2.2   && < 3.3
    - warp                 >= 3.2.28  && < 3.4
