_common: !include "../common.yaml"
name:                boots-web
synopsis:            Web factories.
description:         Provide web factories base on boots.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base          >= 4.10   && < 5

library:
  source-dirs: src
  exposed-modules:
    - Boots.Web
    - Boots.Factory.Web

    - Boots.Factory.Middleware.Random
    - Boots.Factory.Middleware.Error 
    - Boots.Factory.Middleware.Logger 
    - Boots.Factory.Middleware.Trace
  other-modules:
    - Paths_boots_web
  dependencies:
    - boots
    - boots-app
    - bytestring     >= 0.10.8 && < 0.11
    - time           >= 1.8.0  && < 1.9
    - text           >= 1.2.3  && < 1.3
    - salak          >= 0.3.5  && < 0.4
    - vault          >= 0.3.1  && < 0.4
    - http-types     >= 0.12.3 && < 0.13
    - servant-server >= 0.16.2 && < 0.17
    - wai            >= 3.2.2  && < 3.3
    - warp           >= 3.3.0  && < 3.4
    - swagger2       >= 2.4    && < 2.5
    - monad-logger   >= 0.3.30 && < 0.4
    # - servant-swagger

executables:
  demo-web:
    source-dirs:  demo
    ghc-options: -threaded -O2
    main: Main.hs
    dependencies:
    - boots-web
    - boots-app
    - time
    - servant-server

# tests:
#   spec:
#     main: Spec.hs
#     source-dirs:
#       - test
#       - src
#     dependencies:
#       - hspec == 2.*
