_common: !include "../common.yaml"
name:                boots-web
synopsis:            Web factories.
description:         Provide web factories base on boots.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base          >= 4.10   && < 5

library:
  source-dirs: src
  exposed-modules:
    - Boots.Web
    - Boots.Metrics

    - Boots.Endpoint.Class
    - Boots.Endpoint.Health
    - Boots.Endpoint.Info
    - Boots.Endpoint.Logger
    - Boots.Endpoint.Metrics
    - Boots.Endpoint.Refresh

    - Boots.Factory.Web

    - Boots.Middleware.Endpoint
    - Boots.Middleware.Error 
    - Boots.Middleware.Logger 
    - Boots.Middleware.Random
    - Boots.Middleware.Trace
  other-modules:
    - Paths_boots_web
  dependencies:
    - aeson                >= 1.4.4  && < 1.5
    - boots                >= 0.2    && < 0.3
    - boots-app            >= 0.2    && < 0.3
    - bytestring           >= 0.10.8 && < 0.11
    - containers           >= 0.6.0  && < 0.7
    - ekg-core             >= 0.1.1  && < 0.2
    - http-types           >= 0.12.3 && < 0.13
    - monad-logger         >= 0.3.30 && < 0.4
    - salak                >= 0.3.5  && < 0.4
    - servant-server       >= 0.16.2 && < 0.17
    - text                 >= 1.2.3  && < 1.3
    - time                 >= 1.8.0  && < 1.10
    - unordered-containers >= 0.2.10 && < 0.3
    - vault                >= 0.3.1  && < 0.4
    - wai                  >= 3.2.2  && < 3.3
    - warp                 >= 3.2.28 && < 3.4
    # - swagger2       >= 2.4    && < 2.5
    # - servant-swagger

executables:
  demo-web:
    source-dirs:  demo
    ghc-options: -threaded
    main: Main.hs
    dependencies:
    - boots-app      >= 0.2    && < 0.3
    - boots-web      >= 0.2    && < 0.3
    - servant-server >= 0.16.2 && < 0.17
    - time           >= 1.8.0  && < 1.10

# tests:
#   spec:
#     main: Spec.hs
#     source-dirs:
#       - test
#       - src
#     dependencies:
#       - hspec == 2.*
