_common: !include "../common.yaml"
name:                boots-app
synopsis:            Factory for quickly building an application
description:         A quick out-of-box factory using to build application with many useful builtin components based on [boots](https://hackage.haskell.org/package/boots).
category:            Library, Application, Configuration, Logger, Health, Random
<<: *legal
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.9 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Boots

  other-modules:
    
    - Boots.CLI

    - Boots.App
    - Boots.Health
    - Boots.Prelude
    - Boots.Random

    - Boots.App.Internal
    - Boots.Factory.Application
    - Boots.Factory.Logger
    - Boots.Factory.Salak
    - Paths_boots_app
  dependencies:
    - boots                >= 0.2.0.1 && < 0.3
    - bytestring           >= 0.10.8 && < 0.11
    - data-default         >= 0.7.1  && < 0.8
    - exceptions           >= 0.10.2 && < 0.11
    - fast-logger          >= 2.4.16 && < 3.1
    - megaparsec           >= 7.0.5 && < 7.1
    - microlens            >= 0.4.10 && < 0.5
    - mtl                  >= 2.2.2  && < 2.3
    - optparse-applicative >= 0.14.3 && < 0.16
    - salak                >= 0.3.5  && < 0.4
    - salak-yaml           >= 0.3.5  && < 0.4
    - splitmix             >= 0.0.3  && < 0.1
    - text                 >= 1.2.3  && < 1.3
    - unliftio-core        >= 0.1.2  && < 0.2
    - unordered-containers >= 0.2.10 && < 0.3
    - vector               >= 0.12.0  && < 0.13

executables:
  demo-app:
    source-dirs:  demo
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    main: Main.hs
    dependencies:
    - boots-app
    - time >= 1.8.0 && < 1.10