_common: !include "../common.yaml"
name:                boots-app
synopsis:            Startup factories using IoC monad
description:         Provide basic factories base on boots.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base          >= 4.10   && < 5

library:
  source-dirs: src
  exposed-modules:
    - Boots
    - Boots.App
    - Boots.Vault
    - Boots.Random 
    - Boots.Factory.Salak
    - Boots.Factory.Application
    - Boots.Factory.Logger
  other-modules:
    - Boots.App.Internal
    - Paths_boots_app
  dependencies:
    - boots         >= 0.2    && < 0.3
    - exceptions    >= 0.10.2 && < 0.11
    - mtl           >= 2.2.2  && < 2.3
    - data-default  >= 0.7.1  && < 0.8
    - fast-logger   >= 2.4.16 && < 2.5
    - text          >= 1.2.3  && < 1.3
    - menshen       >= 0.0.3  && < 0.1
    - microlens     >= 0.4.10 && < 0.5
    - unliftio-core >= 0.1.2  && < 0.2
    - salak         >= 0.3.5  && < 0.4
    - salak-yaml    >= 0.3.5  && < 0.4
    - splitmix      >= 0.0.3  && < 0.1
    - vault         >= 0.3.1  && < 0.4
    - monad-logger  >= 0.3.30 && < 0.4

executables:
  demo:
    source-dirs:  demo
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    main: Main.hs
    dependencies:
    - boots-app
    - time

# tests:
#   spec:
#     main: Spec.hs
#     source-dirs:
#       - test
#       - src
#     dependencies:
#       - hspec == 2.*
