_common: !include "../common.yaml"
name:                boots-app
synopsis:            Startup factories using IoC monad
description:         Provide basic factories base on boots.
<<: *legal
extra-source-files:
- README.md
dependencies:
  - base >= 4.10 && < 5
  - boots
  - data-default
  - exceptions
  - fast-logger
  - menshen
  - microlens
  - monad-logger
  - mtl
  - salak
  - salak-yaml
  - splitmix
  - text
  - unliftio-core
  - vault

library:
  source-dirs: src
  exposed-modules:
    - Boots
    - Boots.App
    - Boots.Factory.Salak
    - Boots.Factory.Application
    - Boots.Factory.Logger
    - Boots.Factory.Vault
  other-modules:
    - Boots.App.Internal

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
