_common: !include "../common.yaml"
name:                boots-consul
synopsis:            Consul for boots.
description:         Provide consul factories base on boots.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base          >= 4.10   && < 5

library:
  source-dirs: src
  exposed-modules:
    - Boots.Consul
    - Boots.Client
    - Network.Consul
  dependencies:
    - aeson                >= 1.4.4  && < 1.5
    - boots                >= 0.2    && < 0.3
    - boots-app            >= 0.2    && < 0.3
    - boots-web            >= 0.2    && < 0.3
    - bytestring           >= 0.10.8 && < 0.11
    - http-client          >= 0.6.4  && < 0.7
    - salak                >= 0.3.5  && < 0.4
    - servant              >= 0.16.2 && < 0.17
    - servant-client       >= 0.16   && < 0.17
    - text                 >= 1.2.3  && < 1.3
    - unordered-containers >= 0.2.10 && < 0.3

