_common: !include "../common.yaml"
name:                boots
synopsis:            IoC Monad in Haskell
description:         Monad used to encapsulate components, similiar to an IoC container.
category:            Library, Application, Monad, Factory, IoC
<<: *legal
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.9 && < 5
  - exceptions >= 0.10.2 && < 0.11
  - mtl >= 2.2.2 && < 2.3

library:
  source-dirs: src
  exposed-modules:
    - Control.Monad.Factory
    - Control.Monad.Factory.Class

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - boots