_common: !include "../common.yaml"
name:                demo
synopsis:            Web factories.
description:         Provide web factories base on boots.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base >= 4.9 && < 5

executables:
  demo-web:
    source-dirs:  .
    ghc-options: -threaded
    main: Main.hs
    other-modules:
    - Paths_demo
    dependencies:
    - boots-app      >= 0.2    && < 0.3
    - boots-web      >= 0.2    && < 0.3
    - boots-cloud    >= 0.2    && < 0.3
    - servant-server >= 0.16.2 && < 0.17
